version: "3.9"
services:
  db:
    image: prismagraphql/mongo-single-replica:4.4.3-bionic
    container_name: mongodb
    restart: always
    ports:
      - ${DB_PORT}:27017
    environment:
      MONGO_INITDB_DATABASE: ${DB_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}